basePath: /api/v1
definitions:
  blogPost.CreatePostInputDTO:
    properties:
      content:
        type: string
      slug:
        type: string
      title:
        type: string
    type: object
  blogPost.UpdatePostInputDTO:
    properties:
      content:
        type: string
      slug:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API de gerenciamento de artigos de um blog usando Clean Architecture.
  title: Gblog API
  version: "1.0"
paths:
  /posts:
    post:
      consumes:
      - application/json
      description: Cria um novo post no blog salvando-o inicialmente como rascunho
        (draft).
      parameters:
      - description: Dados para a criação do Post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/blogPost.CreatePostInputDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Post criado com sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: JSON inválido
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Erro de regra de negócio
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Criar um Blog Post
      tags:
      - posts
  /posts/{id}:
    delete:
      consumes:
      - application/json
      description: Inativa um post do sistema realizando uma exclusão lógica (soft
        delete).
      parameters:
      - description: ID do Post
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Post removido com sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: ID inválido ou post não encontrado
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Deletar um Blog Post
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: Atualiza o título, slug e conteúdo de um post ativo.
      parameters:
      - description: ID do Post
        in: path
        name: id
        required: true
        type: integer
      - description: Novos dados do Post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/blogPost.UpdatePostInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Post atualizado com sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: ID ou JSON inválido
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Editar um Blog Post
      tags:
      - posts
  /posts/{id}/publish:
    patch:
      consumes:
      - application/json
      description: Altera o status de um post existente para 'published' se ele cumprir
        os requisitos de negócio.
      parameters:
      - description: ID do Post
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Post publicado com sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: ID inválido ou erro na publicação
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Publicar um Blog Post
      tags:
      - posts
swagger: "2.0"
